config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  root "application#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, :controller => :profile do
    resources :snippets do 
      resources :snippet_versions
    end
  end

  get "like/:key/:id", to: "profile#like", as: :like
  get "unlike/:key/:id", to: "profile#unlike", as: :unlike

  post "search", to: "application#search", as: :search

end

app/models/snippet_version.rb
# == Schema Information
#
# Table name: snippet_versions
#
#  id         :integer          not null, primary key
#  content    :text             not null
#  version    :string           default("1.0.0"), not null
#  doc        :string
#  comment    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  snippet_id :integer
#

class SnippetVersion < ApplicationRecord
  VERSION_TYPE = [["big", 0], ["medium", 1], ["small", 2]]
  belongs_to :snippet

  validates :content, presence: true
  validates :version, presence: true


  def type_version=(version)
    version = version.to_i
    last = self.snippet.snippet_versions.last
    if last
      current_version = last.version.split(".").map{ |v| v.to_i }
      if (0..2).include? version
        current_version[version]+= 1
        resetVersion = version+1
        while resetVersion < 3
          current_version[resetVersion] = 0;
          resetVersion+=1
        end
        self.version = current_version.join(".")
      end
    else
      self.version = "1.0.0"
    end
  end

  def type_version
  end

  def getVersionType
    return self.VERSION_TYPE
  end
end

app/controllers/snippet_versions_controller.rb
class SnippetVersionsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:show]
  before_action :set_snippet_version, only: [:show, :edit, :update, :destroy]
  before_action :set_meta_tags_page, only: [:show, :edit, :update, :destroy]
  before_action :check_snippet_version_user, only: [:edit, :update, :destroy, :new]
  before_action :set_user


  # GET /snippet_versions/1
  # GET /snippet_versions/1.json
  def show
  end

  # GET /snippet_versions/new
  def new
    @snippet_version = SnippetVersion.new
    if params[:snippet_id] && Snippet.where(id: params[:snippet_id]).length>0
      @snippet = Snippet.find(params[:snippet_id])
      if @snippet.user != current_user
        flash[:notice] = I18n.t("snippet_version.error.owner")
        redirect_to [@snippet.user, @snippet]
      end
      @snippet_version.snippet_id = params[:snippet_id]
    else
      flash[:notice] = I18n.t("snippet_version.error.no_snippet_id")
      redirect_to root_path
    end
  end


  # POST /snippet_versions
  # POST /snippet_versions.json
  def create
    @snippet = Snippet.find(snippet_version_params[:snippet_id])
    @last_version = @snippet.snippet_versions.last
    puts @last_version.content
    @snippet_version = SnippetVersion.new(snippet_version_params)
    if @last_version.content == snippet_version_params[:content]
      redirect_to [current_user, @snippet], notice: I18n.t("snippet_version.error.same_content")
      return nil
    end
    respond_to do |format|
      if @snippet_version.save
        format.html { redirect_to [current_user, @snippet], notice: I18n.t("snippet_version.success.create") }
        format.json { render :show, status: :created, location: @snippet_version }
      else
        format.html { render :new }
        format.json { render json: @snippet_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snippet_versions/1
  # PATCH/PUT /snippet_versions/1.json
  def update
    respond_to do |format|
      if @snippet_version.update(snippet_version_params)
        format.html { redirect_to [current_user, @snippet], notice: I18n.t("snippet_version.success.update") }
        format.json { render :show, status: :ok, location: @snippet_version }
      else
        format.html { render :edit }
        format.json { render json: @snippet_version.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippet_versions/1
  # DELETE /snippet_versions/1.json
  def destroy
    @snippet_version.destroy
    if @snippet.snippet_versions.empty?
      @snippet.destroy
      respond_to do |format|
        format.html { redirect_to user_path(current_user), notice: I18n.t("snippet_version.success.destroy") }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to [current_user, @snippet], notice: I18n.t("snippet_version.success.destroy") }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snippet_version
      @snippet_version = SnippetVersion.find(params[:id])
      @snippet = Snippet.find(@snippet_version.snippet_id)
    end

    def set_meta_tags_page
      set_meta_tags title: @snippet.name + @snippet_version.version,
                    description: @snippet.description
    end

    def check_snippet_version_user
      if @snippet && @snippet.user != current_user 
        redirect_to [current_user, @snippet], notice: "Vous n'avez pas la permission de modifier ou supprimer cet version de snippet."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_version_params
      params.require(:snippet_version).permit(:content, :doc, :comment, :snippet_id, :type_version)
    end

    def set_user 
      @user = User.find(params[:user_id]); 
    end
end

app/helpers/snippet_versions_helper.rb
module SnippetVersionsHelper
end

app/views/snippet_versions/_form.html.erb
<%= form_for([@snippet_version.snippet.user, @snippet_version.snippet, @snippet_version]) do |f| %>
  <% if @snippet_version.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snippet_version.errors.count, "error") %> prohibited this snippet_version from being saved:</h2>

      <ul>
      <% @snippet_version.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.text_field :comment, class:"form-control", placeholder: t("snippet_version.comment.placeholder") %>
  </div>

  <div class="code-mirror-container">
    <% if @snippet.snippet_versions.last
      content= @snippet.snippet_versions.last.content
    else
      content = ""
    end %>
    <%= f.label :content %>
    <%= f.text_area :content, value: content, class:"codemirror-content", data: {cdMirrorMode: "javascript"} %>
  </div>

  <div class="form-group version-select">
    <%= f.label :type_version %>
      <% SnippetVersion::VERSION_TYPE.each do |v| %>
      <div class="radio-group">
        <label for=""><%= t("snippet_version.type."+v[0]) %></label>
        <input type="radio" name="snippet_version[type_version]" value="<%= v[1] %>" checked>
      </div>
      <% end %>
  </div>

  <%= f.hidden_field :snippet_id %>
  <div class="form-group documentation-group">
    <%= f.label :doc %>
    <label class="mention">Expliquer comment se servir de votre snippet</label>
    <%= f.cktext_area :doc, cols: 40, ckeditor: { toolbar: 'mini' } %>
  </div>

  <div class="actions">
    <%= f.submit "Enregistrer", class:"btn btn-colored" %>
  </div>
<% end %>

app/views/snippet_versions/new.html.erb
<div class="wrapper form materialize">
	
	<%= form_for([@snippet_version.snippet.user, @snippet_version.snippet, @snippet_version ]) do |f| %>

	<%# Title + Actions %>
	<div class="body-top margin-bottom-medium  margin-top-small">
		<h1 class="body-top__content">Nouvelle version</h1>  
		<div class="body-top__action-container">
			<input type="submit" class="btn btn-colored body-top__action">
			<%= link_to "Retour au snippet", [@snippet.user, @snippet], class:"btn btn-colored body-top__action" %>
		</div>
	</div>

	<%# Main Content %>
	<div class="row">

		<%# Error Manage %>
		<% if @snippet_version.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@snippet_version.errors.count, "error") %> prohibited this snippet from being saved:</h2>
		      <ul>
		      <% @snippet_version.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
	  	<% end %>

		<%# Form %>	  	
		<div class="col s5 snippet_show_form">

			<%# Snippet reference for versionning %>
		  	<%= f.hidden_field :snippet_id %>

		  	<%# snippet_versions.comment %>
			<div class="input-field form-item--big">
				<%= f.text_field :comment, class:"validate" %>
				<%= f.label :comment, value: "Décriver votre nouvelle version" %>
			</div>

			<%# Version type => Major | Minor | Patch %>
			<%= f.label :type_version %>
		    <% SnippetVersion::VERSION_TYPE.each do |v| %>
		    <p>
		    <input id="radio-<%= v[0] %>" type="radio" name="snippet_version[type_version]" value="<%= v[1] %>" checked>
		    <label for="radio-<%= v[0] %>"><%= t("snippet_version.type."+v[0]) %></label></p>
		    <% end %>

		</div>

		<%# Code %>
		<div class="col s7 snippet_show_ck">
		  <div class="code-mirror-container">
		    <% content = @snippet.snippet_versions.last ? @snippet.snippet_versions.last.content : "" %>
		    <%= f.label :content %>
		    <%= f.text_area :content, value: content, class:"codemirror-content", data: {cdMirrorMode: "javascript"} %>
		  </div>
		</div>

	</div>

	<%# End form %>
	<% end %>

</div>

app/views/snippet_versions/show.html.erb
<p id="notice"><%= notice %></p>

<h1><span class="code"><%= @snippet.name %></span> - <%= @snippet_version.version %></h1>
<!-- <p>
  <strong>Content:</strong>
  <%= @snippet_version.content %>
</p> -->
<%= form_for @snippet_version do |f| %>
<%= f.text_area :content, class:"codemirror-content", data: {cdMirrorMode: @snippet_version.snippet.lang.cdMirror} %>
<% end %>
<p>
  <strong>Doc:</strong>
  <%= @snippet_version.doc %>
</p>
<%= link_to 'Back', user_snippet_path(user_id: @snippet_version.snippet.user,  id:@snippet_version.snippet_id) %>