config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  root "application#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, :controller => :profile do
    resources :snippets do 
      resources :snippet_versions
    end
  end

  get "like/:key/:id", to: "profile#like", as: :like
  get "unlike/:key/:id", to: "profile#unlike", as: :unlike

  post "search", to: "application#search", as: :search

end

app/models/snippet.rb
# == Schema Information
#
# Table name: snippets
#
#  id          :integer          not null, primary key
#  description :string
#  abstract    :boolean          default("false")
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  lang_id     :integer
#  user_id     :integer
#  private     :boolean          default("false")
#

class Snippet < ApplicationRecord
  has_many :snippet_versions, :dependent => :destroy
  has_many :likes, :as => :likable
  belongs_to :lang
  belongs_to :user
  accepts_nested_attributes_for :snippet_versions

  validates :name, presence: true

  scope :not_private, -> { where private: false }

  def actual
    self.snippet_versions.last
  end

  def to_s
    self.name
  end

end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  load_and_authorize_resource


  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_snippet, only: [:show, :edit, :update, :destroy]
  before_action :set_meta_tags_page, only: [:show, :edit, :update, :destroy]
 
  before_action :set_user
  before_action :check_snippet_user, only: [:edit, :update, :destroy]

  # GET /snippets
  # GET /snippets.json

  def index
    @snippets = @user.snippets; 
    @snippets = @snippets.not_private unless @user.id == current_user.id
    respond_to do |format|
      format.html
      format.json { render :json => @snippets }
    end
  end

  # GET /snippets/1
  # GET /snippets/1.json
  def show
    if current_user && current_user.id != @user.id && @snippet.private
      throw ActiveRecord::RecordNotFound
    end
  end

  # GET /snippets/new
  def new
    @snippet = Snippet.new(user: current_user)
  end

  # GET /snippets/1/edit
  def edit
  end

  # POST /snippets
  # POST /snippets.json
  def create
    @snippet = Snippet.new snippet_params.except(:snippet_versions_attributes)

    if !validate_params_create
      flash[:notice] = "Il faut rentrer du contenu dans votre snippet"
      redirect_to new_user_snippet_path(user_id: current_user)
    else

      @snippet.user = current_user
      respond_to do |format|
        if @snippet.save && @snippet.update(snippet_params.slice(:snippet_versions_attributes))
          format.html { redirect_to user_snippet_path(id:@snippet.id), notice: 'Snippet was successfully created.' }
          format.json { render :show, status: :created, location: @snippet }
        else
          format.html { render :new }
          format.json { render json: @snippet.errors, status: :unprocessable_entity }
        end
      end

    end
    
  end

  # PATCH/PUT /snippets/1
  # PATCH/PUT /snippets/1.json
  def update
    respond_to do |format|
      if @snippet.update(snippet_params)
        format.html { redirect_to user_snippet_path(user_id: @snippet.user, id:@snippet), notice: 'Snippet was successfully updated.' }
        format.json { render :show, status: :ok, location: @snippet }
      else
        format.html { render :edit }
        format.json { render json: @snippet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snippets/1
  # DELETE /snippets/1.json
  def destroy
    @snippet.destroy
    respond_to do |format|
      format.html { redirect_to user_snippets_path(user_id: current_user), notice: 'Snippet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_snippet
      @snippet = Snippet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snippet_params
      params.require(:snippet).permit(:description, :lang_id, :abstract, :name, :private, snippet_versions_attributes: [:content, :version, :doc, :comment])
    end

    def set_meta_tags_page
      set_meta_tags title: @snippet.name,
                    description: @snippet.description
    end

    def validate_params_create
      if snippet_params[:snippet_versions_attributes]["0"][:content].to_s.empty?
        return false
      else
        return true
      end
    end

    def check_snippet_user
      if @user.id != current_user.id
        redirect_to [@snippet.user, @snippet], notice: "Vous n'avez pas la permission de modifier ou supprimer ce snippet."
      end
    end

    def set_user 
      @user = User.find(params[:user_id]); 
    end

end

app/helpers/snippets_helper.rb
module SnippetsHelper
  def privateLib(privateAttr)
    if privateAttr
      "private"
    else
      "public"
    end
  end
end

app/views/snippets/edit.html.erb
<%= render template: "application/sidebar",	locals: { user:@user } %>

<div class="body-aside">
	
	<div class="form materialize ">
		<%= form_for([@snippet.user, @snippet]) do |f| %>
		<div class="body-top">
			<h1 class="body-top__content">Paramètres - <%= @snippet.name %></h1>	
			<div class="body-top__action-container">
				<%= link_to t("snippet.actions.back"), [@snippet.user, @snippet], class:"btn btn-colored btn--back body-top__action" %>
				 <%= f.submit t("actions.save") , class:"btn btn-colored body-top__action" %>
			</div>
		</div>

	
		<div class="form margin-top-big">
		
			<% if @snippet.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>
				<ul>
				<% @snippet.errors.full_messages.each do |message| %>
					<li><%= message %></li>
				<% end %>
				</ul>
			</div>
			<% end %>

			
			<div class="input-field form-item--md">
				<%= f.text_field :name, class:"validate" %>
				<%= f.label :name %>
			</div>
			
			<div class="input-field form-item--md">
				<% langs_array = @languages.all.map { |language| [language.lib, language.id] } %>
				<%= select_tag "snippet[lang_id]", options_for_select(langs_array, @snippet.lang_id) %>
				<%= f.label :lang_id %>
			</div>	

			<p>
				<%= f.check_box :private, class:"filled-in", checked: true %>
				<%= f.label :private %>
			</p>
			<p class="form-item__mention form-item__mention--danger">Mettre en privé signifie que personne à part vous pourra visualiser ce contenu</p>
			<div class="divider margin-bottom-medium margin-top-medium"></div>
			
			<div class="input-fiel">
			<%= cktext_area :snippet, :description, cols: 40, ckeditor: { toolbar: 'mini' }, value: "Describe your snippet" %>
			</div>
		</div> 
		<% end %>
	</div>
</div>

app/views/snippets/index.html.erb
<%= render template: "application/sidebar",  locals: { user:@user } %>

<div class="body-aside">

	<div class="body-top">
		<h1 class="body-top__content"><%= t("snippet.index.title") %></h1>	
		<div class="body-top__action-container">
			<% if @user.id == current_user.id %>
			<%= link_to t("snippet.actions.new"), new_user_snippet_path(user_id: @user), class:"btn btn-colored body-top__action" %>
			<% end %>
		</div>
	</div>
	
	<%= render template: "application/search-helper",  locals: { user:@user, snippets: @snippets } %>

	 <div id="snippetsList" class="items">
	 	 <% @snippets.each do |snippet| %>
    		<div class="items__item">
    			<div class="items__item-head">
    				<p class="items_item-title"><%= snippet.name %></p>
    				<% if snippet.private %>
					<%# TODO: Integrate private %>
    				<% end %>
    				<% if snippet %>
    				<%# TODO: Implement Starred button %>
    				<% end %>
    			</div>
				
				<div class="items__item-body">
					<div class="items__item-content"><%= raw snippet.description %></div>
					<div class="language-list">
						<ul>
							<li style="background-color:<%= snippet.lang.bgColor %>; color:<%= snippet.lang.color %>;" class="language-list__item"><%= snippet.lang.cd.upcase %></li>
						</ul>
					</div> 	
				</div>

				<%= link_to "", user_snippet_path(id: snippet, user_id: snippet.user), class:"items__item-show" %>
    		</div>
    	<% end %>
    	<% if current_user && current_user.id==@user.id && @snippets.length == 0 %>
    	<p>Vous n'avez pas encore de snippets ! </p>
    	<%= link_to "Créer un snippet !", new_user_snippet_path(user_id: @user), class:"btn btn-colored margin-top-small" %>
    	<% end %>

    	<button @click="onClickButton">Decode</button>
	 </div>

</div>

app/views/snippets/new.html.erb
<div class="wrapper form materialize">
	<%= form_for([@snippet.user, @snippet]) do |f| %>

	<div class="body-top margin-bottom-medium margin-top-small">
		<h1 class="body-top__content">Nouveau snippet</h1>  
		<div class="body-top__action-container">
			<input type="submit" value="Enregister" class="btn btn-colored body-top__action">
			<%= link_to "Retour aux snippets", @user, class:"btn btn-colored body-top__action" %>

		</div>
	</div>
	<div class="row">
		<% if @snippet.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(snippet.errors.count, "error") %> prohibited this snippet from being saved:</h2>
	      <ul>
	      <% @snippet.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  	<% end %>
		<div class="col s5 snippet_show_form">
			
			<p class="form-item__info">Un Snippet ne peut être composé que d’un seul language. Par défaut le snippet sera noté de la version 1.0.0. Vous pourrez faire évoluer votre snippet plus tard à l’aide de l’utilitaire de version.</p>

			 <div class="input-field form-item--big">
				<%= f.text_field :name, class:"validate" %>
				<%= f.label :name %>
			</div>

			<div class="input-field form-item--big">
				<% langs_array = @languages.all.map { |language| [language.lib, language.id] } %>
				<%= select_tag "snippet[lang_id]", options_for_select(langs_array, @snippet.lang_id) %>
				<%= f.label :lang_id %>
			</div>  
			
			<p><%= f.check_box :private, class:"filled-in", checked: false %><%= f.label :private %></p>
			<p class="form-item__mention form-item__mention--danger">Mettre en privé signifie que personne à part vous pourra visualiser ce contenu</p>
			<div class="divider margin-bottom-medium margin-top-medium"></div>
			
			<p class="form-item__info">Rentrer une description de snippet est fortement conseillé. Elle permet au visiteur d’aisément comprendre l’utilité de votre snippet.</p>
			<div class="">
				<%= f.cktext_area :description, value: "Describe your snippet", class:"materialize-textarea" %>
			</div>

		</div>
		<div class="col s7 snippet_show_ck">
			<% snip = SnippetVersion.new %>
			<%= f.fields_for :snippet_versions, snip do |ff| %>
			<%= ff.text_area :content, placeholder: "Content", class:"codemirror-content", data: {cdMirrorMode:"javascript"} %>
			<%= ff.hidden_field :version %>
			<%= ff.hidden_field :label, value:"First Version" %>
			<% end %><!-- fields for -->
		</div>
	</div>


	<% end %>

</div>

app/views/snippets/show.html.erb
<%= render template: "application/sidebar",  locals: { user:@user } %>

<div class="body-aside">
    <div class="body-top">
      <h1 class="body-top__content"><%= @snippet.name %></h1>  
      <div class="body-top__action-container">
        <%= link_to "Paramètres", edit_user_snippet_path(user_id: @snippet.user, snippet_id:@snippet), class:"btn btn-dark body-top__action" %>
        <%= link_to "+ Nouvelle version", new_user_snippet_snippet_version_path(user_id: @snippet.user, snippet_id:@snippet), class:"btn btn-dark body-top__action" %>
        <%= link_to "Supprimer Snippet", user_snippet_path(user_id: @snippet.user, id: @snippet), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn__ico btn__ico--danger body-top__action" %>
      </div>
    </div>

  
    <div class="body-aside__description">
      <%= raw @snippet.description %>
      <div class="language-list">
        <ul><li class="language-list__item" style="background-color: <%= @snippet.lang.bgColor %>; color: <%= @snippet.lang.color %>"><%= @snippet.lang.cd %></li></ul>
      </div>  
    </div> 

    <div>
      <div class="materialize form">
        <div id="select_container" class="input-field form-item--sm">
          <select id="select_version">
            <% @snippet.snippet_versions.each_with_index do |v, i| %>
            <% if i == @snippet.snippet_versions.length-1 %>
              <option selected value="<%= i %>">v.<%= v.version %></option>
            <% else %>
              <option value="<%= i %>">v.<%= v.version %></option>
            <% end %>
            <% end %>
          </select>
        </div>  
      </div>
      <div id="code">
      <% @snippet.snippet_versions.each_with_index do |v, i| %>
        <div class="code-version <% if i == @snippet.snippet_versions.length-1 %>visible<% end %>" data-id="<%= v.id %>">
          <textarea rows="8" cols="80" class="codemirror-content" data-cdMirrorMode="<%= @snippet.lang.cdMirror%>"><%= v.content %></textarea>
        </div>
      <% end %>
      </div>
    </div>

</div>