config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Ckeditor::Engine => '/ckeditor'

  root "application#home"

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" } do
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :users, :controller => :profile do
    resources :snippets do 
      resources :snippet_versions
    end
  end

  get "like/:key/:id", to: "profile#like", as: :like
  get "unlike/:key/:id", to: "profile#unlike", as: :unlike

  post "search", to: "application#search", as: :search

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include CanCan::ControllerAdditions

  protect_from_forgery with: :exception
  before_action :get_lang
  before_action :configure_devise_parameters, if: :devise_controller?
  before_action :default_meta_tags
  skip_before_action :verify_authenticity_token, only: :search

  # set_meta_tags :title => 'Code Keeper',
  #               :description => "Super description",
  #               :keywords => 'Code Keeper, version, sauvegarde, github'


  rescue_from CanCan::AccessDenied do |exception|
    # flash[:warning] = exception.message
    flash[:notice] = exception.message
    #Rails regarde dans le mauvais fichier de route (celui de rails_admin donc on redirige en absolu)
    if current_user
      redirect_to "/"
    else
      redirect_to "/users/sign_in"
    end
  end

  def search
    if params[:text] && params[:text]!=""
      name = params[:text]
      @snippets = Snippet.where("LOWER(name) LIKE ? AND private=false", "%#{name.downcase}%")
    end
    if !@snippets || params[:text]==""
      render json: false
    else
      render json: @snippets.to_json(include: :lang)
    end
  end

  def home
    @snippets = Snippet.where(private: false).last(6)
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname])
  end


  def default_meta_tags
    set_meta_tags site: 'Code Keeper',
                  description: t("meta_description"),
                  keywords: 'Code Keeper, version, sauvegarde, github',
                  viewport: "width=device-width, user-scalable=no"
  end

  private
    def get_lang
      @languages = Lang.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/header.html.erb
<header class="materialize navbar-fixed">
  <% if user_signed_in? %>
  <ul id="dropdown-snippet" class="dropdown-content">
    <li><%= link_to "Create", new_user_snippet_path(user_id: current_user) %></li>
    <li><%= link_to "All", user_snippets_path(user_id: current_user) %></li>
  </ul>
  <ul id="dropdown-account" class="dropdown-content">
    <li><%= link_to t("user.profile"), user_path(current_user) %></li>
    <li><%= link_to t("devise.sessions.sign_out"), destroy_user_session_path, method: :delete %></li>
  </ul> 
  <% end %>
  <nav>
    <div class="nav-wrapper">
      <%= link_to root_path, class:"brand-logo" do %>
        <%= image_tag "logo-plain.png", alt:t("title") %>
      <% end %>

      <%= form_tag search_path, class:" form-search hide-on-med-and-down", remote: true do %>
      <div class="form-item__container">
        <input id="search-input" placeholder="Rechercher" name="text" class="form-item form-search" type="search" required autofocus="true">
        <!-- <button class="btn btn-colored" id="sidebar-right-btn">Filtres</button> -->
      </div>
      <% end %>
      
      <ul class="right hide-on-med-and-down">
        <% if user_signed_in? %>
            <li><a class="dropdown-button" href="#!" data-beloworigin="true" data-activates="dropdown-snippet">Snippets<i class="material-icons right fa fa-caret-down" aria-hidden="true"></i></a></li>
            <li><a class="dropdown-button" href="#!" data-beloworigin="true" data-activates="dropdown-account">Mon Compte<i class="material-icons right fa fa-caret-down" aria-hidden="true"></i></a></li>
        <% else %>
            <li><%= link_to t("devise.sessions.new.sign_in"), new_user_session_path %></li>
            <li><%= link_to t("devise.registrations.new.sign_up"), new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/application/home.html.erb
<div id="landing" class="vertical-center">
  <div>
    <%= image_tag "logo.png", class:"margin-bottom-small" %>
    <h1><%= t "title" %></h1>
    <p class="description"><%= t "description" %></p>
    <% if !user_signed_in? %>
    <div class="actions">
      <%= link_to t("devise.sessions.new.sign_in"), new_user_session_path, class:"btn btn-dark big" %>
      <%= link_to t("actions.start"), new_user_registration_path, class:"btn btn-colored big" %>
    </div>
    <% end %>
    <!-- <p class="mention"><%= t "actions.more" %></p>
    <a href="#lastSnippet" class="scroll">Scroll to lastsnippet</a> -->
  </div>
</div>

app/views/application/search-helper.html.erb
<div class="search-helper">
	<div class="search-helper__item">
		<label for="" class="search-helper__item-label">Recherche par tags</label>
		<input type="text" class="form-item form-item__search">
	</div>

	<div class="search-helper__item">
		<label for="" class="search-helper__item-label">Trier par</label>
		<div class="form-item form-item__select-container">
		  <select class="form-item__select">
		    <option value="alpha">Ordre alphabétique</option>
		    <option value="starred">Nombre de starred</option>
		    <option value="date">Date</option>
		  </select>
		</div>
	</div>
	
	<div class="search-helper__item">
		<label for="" class="search-helper__item-label">Ordre</label>
		<input type="text" class="form-item form-item__search">
	</div>

	<div class="search-helper__item">
		<label for="" class="search-helper__item-label">Filtrer</label>
		<input type="text" class="form-item form-item__search">
	</div>
</div>

app/views/application/sidebar.html.erb
<section class="sidebar">

	<div class="profil">
		<%= image_tag "avatar", class:"profil__avatar" %>
	
		<div class="profil__info-container">
			<p class="profil__pseudo"><%= user.nickname %></p>
			<p class="profil__fullname"><%= user.fullname %></p>
		</div>
		
		<% if current_user && user.id == current_user.id %>
			<%= link_to "", edit_user_path(id: current_user.id), class:"profil__edit-btn" %>
		<% else %>
			<%# 
			TODO: Implement Relation User has_many likes  
			<a href="" class="profil__starred-btn"></a>
			%>
		<% end %>
		
	</div>

	<% if user.description %>
	<div class="profil-description">
		<p class="profil-description__content"><%= user.description %></p>


		<%#

		TODO: Implement User has_many languages

		<div class="language-list">
			<ul>
				<li class="language-list__item">JS</li>
				<li class="language-list__item">JS</li>
				<li class="language-list__item">JS</li>
				<li class="language-list__item">JS</li>
			</ul>
		</div> 	

		%>
	</div>
	<% end %>

	<div class="social-list">
		<a href="<%= user.url_site %>" class="social-list__item"><%= user.url_site %></a>
		<a href="<%= user.url_github %>" class="social-list__item"><%= user.url_github %></a>
	</div>

	<div class="sidebar__menu">
		<ul>
			<li>
			<%= link_to "Snippets", user_snippets_path(user_id: @user), class:"sidebar__menu-item"  %>
			</li>

			<%#
			TODO: Implement Object  			
			<li><a class="sidebar__menu-item" href="">Objects</a></li>
			%>

			<li><a class="sidebar__menu-item" href="">Starred</a></li>
		</ul>
	</div>
	
</section>